Feature/mainpage
dsm-pear/user_frontend pull request #105
Opened 2020-12-30 23:54 UTC by oajh04

2020-12-31 01:54 UTC, woochanleee requested changes

2020-12-31 01:54 UTC, woochanleee commented on src/Components/Main/Questions.js
> +            QuestApi()
Promise로 리턴되는데 그럼 비동기인데 아무 처리도 안해줘도 될까요?
서버 요청이 끝나기 전에 `setModalVisible` 함수가 실행되는 문제가 발생하지 않을까요?

2020-12-31 01:54 UTC, woochanleee commented on src/Components/Main/Questions.js
> +        Number(response.status) === 200 ? setMessage("버그 & 문의 사항이 접수 되었습니다") : setMessage("오류가 발생햇습니다")
에러처리를 이런식으로 해도 잘 작동하나요?
고민해보면 좋겠네요

2021-01-07 06:17 UTC, LeeSeongJinCa requested changes

2021-01-07 06:17 UTC, LeeSeongJinCa commented on src/Components/Main/Questions.js
>              setModalVisible(true);
if 랑 else 랑 둘다 setModalVisible(true) 해줄거면 if문 밖으로 빼도 될거 같아요.

2021-01-07 06:17 UTC, LeeSeongJinCa commented on src/Components/Main/Questions.js
> +        Number(response.status) === 200 ? setMessage("버그 & 문의 사항이 접수 되었습니다") : setMessage("오류가 발생햇습니다")
같은 의견이고 위에서는 if else로 처리했으면 에러 처리도 if elseif else 이렇게 처리하는게 더 좋다고 생각합니다.

2021-01-07 06:17 UTC, LeeSeongJinCa commented on src/Components/Modal/ReportWritingModal.js
>  import { bfchecked } from "../../assets";
하나의 폴더에서 가져오는 import문은 하나의 { .. }로 쓰는게 맞습니다.
-> import { Close, searchImg, ..., bfchecked } from '../../assets/';

2021-01-07 06:17 UTC, LeeSeongJinCa commented on src/Components/Modal/ReportWritingModal.js
> +            <span>{toggled === !true && <img src={Close} alt="Close" />}</span>
{toggled === false && <img ... />}
or
{!toggled && <img ... />}
를 추천합니다.

2021-01-07 06:17 UTC, LeeSeongJinCa commented on src/Components/Modal/ReportWritingModal.js
> +      {toggled === true && (
여기도 위와 같이
{toggled ? (..) : (..)}
{toggled && (..)}
로 사용하는 것을 추천합니다.

2021-01-07 11:24 UTC, oajh04 commented on src/Components/Main/Questions.js
> +        Number(response.status) === 200 ? setMessage("버그 & 문의 사항이 접수 되었습니다") : setMessage("오류가 발생햇습니다")
수정해보겠습니다

2021-01-10 12:13 UTC, woochanleee approved these changes

2021-01-10 12:13 UTC, woochanleee commented on src/Components/Main/Questions.js
> +            QuestApi()
- async 함수의 리턴값은 Promise임
- 따라서 QuestApi 함수가 끝나기 전에 setModalVisible(true); 가 실행됨

2021-01-13 02:49 UTC, merged