Feature/notice
dsm-pear/user_frontend pull request #24
Opened 2020-11-07 11:46 UTC by oajh04

Notice UI

2020-11-07 13:10 UTC, woochanleee approved these changes

2020-11-11 00:07 UTC, LeeSeongJinCa requested changes

2020-11-11 00:07 UTC, LeeSeongJinCa commented on src/Components/Notice/Notice.js
> +        if(show===true){
if (show) 로 축약 가능

2020-11-11 00:07 UTC, LeeSeongJinCa commented on src/Components/Notice/Notice.js
> +                                <S.NoticeC onClick={()=>onOld()}>오래된순</S.NoticeC>
() => callback() 이런 구문은 익명 함수를 하나 더 생성하므로 메모리를 1개 더 잡아먹습니다.
onClick={onNew}
onClick={onOld} 로 바꿔도 가능합니다.

2020-11-11 00:07 UTC, LeeSeongJinCa commented on src/Components/Notice/NoticeContainer.js
> +                </S.ContainerContant>
여러 개의 똑같은 JSX를 사용하려면 기본 data를 객체나 배열로 만들어서 관리하고 map을 이용해 랜더링하는 것이 가독성과 코드 길이를 줄일 수 있습니다.
리뷰하는데도 불편함을 줄 수 있어요.

2020-11-11 00:07 UTC, LeeSeongJinCa commented
Resolve conflicts 눌러서 충돌 파일 해결해주세요~

2020-11-11 02:17 UTC, oajh04 commented on src/Components/Notice/Notice.js
> +        if(show===true){
수정했습니다!

2020-11-11 06:19 UTC, sema0710 commented on src/Routers/index.js
> +export { default as AdminRouter } from "./AdminRouter";
admin router는 왜 있는건가요?

2020-11-11 06:19 UTC, sema0710 commented on src/Routers/index.js
> +export { default as AdminRouter } from "./AdminRouter";
admin이랑 user 쪽이랑 버킷 따로 파고, 레포도 다른데 왜 같이 있는지 궁금하네요

2020-11-11 13:55 UTC, LeeSeongJinCa approved these changes
굳입니다~

2020-11-11 23:59 UTC, merged