라우터 주소 수정
dsm-pear/user_frontend pull request #25
Opened 2020-11-10 13:40 UTC by silverbeen

2020-11-10 14:05 UTC, woochanleee approved these changes

2020-11-10 14:05 UTC, woochanleee commented on src/Components/Login/InputCom.js
> +          style={{ background: bcolor }}
인라인 스타일로 주는것보다 스타일드컴포넌트에 props로 적용하는게 나을것 같단 의견입니당

2020-11-11 00:13 UTC, LeeSeongJinCa requested changes
고치고 다시 review 날려주세요.

2020-11-11 00:13 UTC, LeeSeongJinCa commented on src/Components/Login/InputCom.js
> +          style={{ background: bcolor }}
그리고 위에 onClick 이벤트 함수 이름이 Chick인데.. Click 하려던건가요..?

2020-11-11 00:13 UTC, LeeSeongJinCa commented on src/Components/Login/InputCom.js
> +      ) : null}
3항 연산자로 조건부 랜더링을 할 때 두 번째 랜더링에 null을 랜더링하는 것은 아래처럼 축약할 수 있습니다.
{button && (조건부 랜더링)}

2020-11-11 00:13 UTC, LeeSeongJinCa commented on src/Components/ViewReport/Report/MainReport.js
> +      <Globlastyle />
이 컴포넌트에서만 createGlobalStyle을 사용한 이유가 있나요?

2020-11-11 05:35 UTC, silverbeen commented on src/Components/ViewReport/Report/MainReport.js
> +      <Globlastyle />
음... 바디에다가 넣어 주려고 했는데 생각해보니까 필요가 없었습니다..

2020-11-11 05:36 UTC, silverbeen commented on src/Components/Login/InputCom.js
> +      ) : null}
넵 수정하겠습니다.

2020-11-11 06:38 UTC, silverbeen commented on src/Components/Login/InputCom.js
> +          style={{ background: bcolor }}
넵 수정하겠습니다.

2020-11-12 02:07 UTC, sema0710 commented on src/Components/Login/InputCom.js
> +      console.log("강은빈 멍청이");
console.log 지워주세요 ㅋㅋㅋ

2020-11-12 02:07 UTC, sema0710 commented on src/Components/Login/InputCom.js
> +          style={{ background: bcolor }}
파일 이름이 InputCom인데 Com이 무슨 의미인가요?

2020-11-12 02:40 UTC, silverbeen commented on src/Components/Login/InputCom.js
> +      console.log("강은빈 멍청이");
넵 ㅋㅋ..

2020-11-12 05:00 UTC, LeeSeongJinCa approved these changes
굳~

2020-11-12 05:00 UTC, LeeSeongJinCa commented on src/Components/ViewReport/Report/Comments.js
> +      <S.date></S.date>
styled-component의 네이밍 규칙은 첫 글자가 대문자입니다~

2020-11-12 05:01 UTC, silverbeen commented on src/Components/ViewReport/Report/Comments.js
> +      <S.date></S.date>
넵 수정하겠습니당

2020-11-12 05:38 UTC, sema0710 approved these changes

2020-11-13 00:58 UTC, merged