Feature/search result
dsm-pear/user_frontend pull request #34
Opened 2020-11-16 04:26 UTC by oajh04

2020-11-16 04:57 UTC, sema0710 requested changes

2020-11-16 04:57 UTC, sema0710 commented on src/Components/SearchResult/SearchResult.js
> +                        }
함수로 빼내는게 어떨까요?

2020-11-16 04:57 UTC, sema0710 commented on src/Components/SearchResult/SearchResultLanguage.js
> +                    const color = data.bdc === "팀" ? "#6192f3" : data.bdc === "개인" ? "#27d5b1" : "#5955d8";
1.bdc naming 수정해주세요, 무슨 의미인지 이해가 안갑니다.
2.styled-component props로 color를 넘기면 style={{}}를 이용하지 않아도 색깔을 바꿀 수 있습니다.

2020-11-16 04:57 UTC, sema0710 commented on src/Components/SearchResult/SearchResultLanguage.js
> +                                    [{data.bdc}]
[{}] <-- 이렇게 한 이유가 있나요?

2020-11-16 04:57 UTC, sema0710 commented on src/Components/SearchResult/SearchResultProfile.js
> +            }
이렇게 작성할 경우 컴포넌트 리렌더 될때마다 함수가 다시 선언됩니다.
함수로 빼낸 후 useCallback으로 묶은 후에 사용하는것을 추천합니다.

2020-11-16 08:17 UTC, oajh04 commented on src/Components/SearchResult/SearchResultLanguage.js
> +                                    [{data.bdc}]
아 이건 [팀] 이런식으로 출력되어야해서 이렇게 했습니다

2020-11-16 08:17 UTC, oajh04 commented on src/Components/SearchResult/SearchResultLanguage.js
> +                    const color = data.bdc === "팀" ? "#6192f3" : data.bdc === "개인" ? "#27d5b1" : "#5955d8";
둘다 수정하겠습니다.

2020-11-16 08:18 UTC, oajh04 commented on src/Components/SearchResult/SearchResult.js
> +                        }
함수로 빼면 그 자리에 
{
    함수이름()
}

이런식으로 하면 될까요?

2020-11-16 08:18 UTC, oajh04 commented on src/Components/SearchResult/SearchResultProfile.js
> +            }
한번 해보겠습니다!

2020-11-16 10:04 UTC, LeeSeongJinCa commented on src/Components/SearchResult/SearchResult.js
> +                        }
넵

2020-11-16 10:05 UTC, woochanleee approved these changes
준상이가 말한거 수정하고 고고

2020-11-16 10:06 UTC, LeeSeongJinCa approved these changes

2020-11-16 12:38 UTC, sema0710 commented on src/Components/SearchResult/SearchResultLanguage.js
> +                                    [{data.bdc}]
아 ㅋㅋㅋㅋ 알겠습니다

2020-11-17 01:59 UTC, sema0710 approved these changes

2020-11-17 01:59 UTC, sema0710 commented
나이스

2020-11-17 10:25 UTC, merged