Feature/notice
dsm-pear/user_frontend pull request #85
Opened 2020-11-29 02:50 UTC by oajh04

2020-11-29 13:32 UTC, woochanleee approved these changes

2020-11-29 23:46 UTC, sema0710 requested changes

2020-11-29 23:46 UTC, sema0710 commented on src/Components/Notice/Notice.js
> +    const [ a, seta ] = useState(1);
네이밍 수정 해주세요

2020-11-29 23:46 UTC, sema0710 commented on src/Components/Notice/NoticeContent.js
> +    */
지워주세요

2020-11-30 00:05 UTC, oajh04 commented on src/Components/Notice/Notice.js
> +    const [ a, seta ] = useState(1);
수정했습니다!

2020-11-30 00:05 UTC, oajh04 commented on src/Components/Notice/NoticeContent.js
> +    */
지웠습니다!

2020-11-30 04:59 UTC, LeeSeongJinCa approved these changes
👍

2020-12-02 06:09 UTC, merged